backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: auutstudio/app-poem
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Poets"
    name: "poets"
    folder: "src/poets"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Website", name: "poetsite", widget: "string", required: false }
      - { label: "Bio", name: "poetbio", widget: "markdown", required: false }
      - { label: "Image", name: "psrc", widget: "image", required: false }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        required: false
        create: true
        options: ["Tags", "poets"]
  - label: "Poems"
    name: "poems"
    identifier_field: id
    folder: "src/poems"
    format: json
    slug: "{{author}}-{{id}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "ID", name: "id", widget: "number", value_type: "int", min: 1, required: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Page", name: "goto", widget: "string", required: false }
      - { label: "Publish Year", name: "date", widget: "number", required: false }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Lat", name: "lat", hint: "(eg 37.xxx)", widget: "number", value_type: "float" }
      - { label: "Long", name: "lng", hint: "(eg -122.xxx)", widget: "number", value_type: "float" }
      - { label: "Icon", name: "color", hint: "type 'default', otherwise enter a color", widget: "string", required: false }
      - { label: "Scroll?", name: "scroll", widget: "boolean", required: false }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        required: false
        create: true
        options: ["Tags", "poems"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
