backend:
  # Use netlify identity as backend
  # name: git-gateway
  # branch: master
  ### enable below lines for github integration ###
  name: github
  repo: auutstudio/app-poem
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Poets"
    name: "poets"
    folder: "src/poets"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name", name: "poetname", widget: "string" }
      - { label: "Website", name: "poetsite", widget: "string" }
      - { label: "Bio", name: "poetbio", widget: "markdown" }
      - { label: "Image", name: "psrc", widget: "string" }
  - label: "Poems"
    name: "poems"
    folder: "src/poems"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Lat", name: "lat", widget: "number" }
      - { label: "Long", name: "lng", widget: "number" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Page", name: "plink", widget: "string" }
      - { label: "Publish Year", name: "date", widget: "number" }
      - { label: "Icon", name: "color", widget: "string" }
      - { label: "Scrollable", name: "scroll", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
